language: python
python:
- '3.7'
install: pip install -r requirements.txt
script:
- python manage.py test
env:
  global:
  - SECRET_KEY=notSoSecret0b761osmjjjqu_oz4&81hye7zgnr4quz4rv7hg9yw8
  - DEBUG=True
before_script:
- python manage.py migrate